2023-07-08 18:32:06,813 - scheduler - INFO - #----------------------- Inicia proceso de Scheduler
2023-07-08 18:32:06,813 - scheduler - INFO - Orden a procesar tareas
2023-07-08 18:32:06,816 - scheduler - INFO - detener................
2023-07-08 18:32:16,817 - scheduler - INFO - continuar................
2023-07-08 18:32:17,288 - scheduler - INFO - Modulo: <module 'jobs.processFile.process_file' from 'd:\\WorkSpace\\WS_REACT_PRANICAL\\JobScheduler\\backend\\jobs\\processFile\\process_file.py'>
2023-07-08 18:32:17,288 - scheduler - INFO - Instancia: <class 'jobs.processFile.process_file.ProcessFile'>
2023-07-08 18:32:17,289 - scheduler - INFO - Operacion: GetList
2023-07-08 18:32:38,365 - scheduler - ERROR - Error.........................: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder
Traceback (most recent call last):
  File "d:\WorkSpace\WS_REACT_PRANICAL\JobScheduler\backend\routes\chains_routes.py", line 95, in process
    spooler.process()
  File "d:\WorkSpace\WS_REACT_PRANICAL\JobScheduler\backend\spooler_task.py", line 41, in process
    self.process_job(self.get_job(self.current_job))
  File "d:\WorkSpace\WS_REACT_PRANICAL\JobScheduler\backend\spooler_task.py", line 65, in process_job
    result = instance.spooler_process(instance)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\WorkSpace\WS_REACT_PRANICAL\JobScheduler\backend\jobs\processFile\process_file.py", line 14, in spooler_process
    list = self.getListFiles(self)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\WorkSpace\WS_REACT_PRANICAL\JobScheduler\backend\jobs\processFile\process_file.py", line 40, in getListFiles
    client = self.getClient(self, server, port, user, password)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\WorkSpace\WS_REACT_PRANICAL\JobScheduler\backend\jobs\processFile\process_file.py", line 29, in getClient
    client.connect(server, port, username=user, password=password)
  File "C:\Python311\Lib\site-packages\paramiko\client.py", line 386, in connect
    sock.connect(addr)
TimeoutError: [WinError 10060] Se produjo un error durante el intento de conexión ya que la parte conectada no respondió adecuadamente tras un periodo de tiempo, o bien se produjo un error en la conexión establecida ya que el host conectado no ha podido responder

2023-07-08 18:32:38,369 - scheduler - INFO - Proceso termino con error.
